import 'components/song_card.dart';


  List<SongCard> songCards = [
    SongCard(
      country: 'ALBANIA',
      singer: 'Besa',
      songName: 'Titan',
      videoLink: 'https://youtu.be/nrjFhjpm7D8?si=MfIJ_qvdHb8jSykc',
      info: '"Titan" (stylised as "TiTAN") is a song by Albanian singer and songwriter Besa Kokëdhima. Self-described as a ballad "with a lot of contrast", it was composed by Kokëdhima, Kledi Bahiti and Fabrice Grandjean, with lyrics by Gia Koka. It is set to represent Albania in the Eurovision Song Contest 2024, following the selection of the song\'s Albanian-language version "Zemrën n\'dorë" (pronounced [ˈzɛmɾən nˈdɔɾ(ə)]; transl. "Heart in hand") at the 62nd edition of the music competition Festivali i Këngës.',
    ),
    SongCard(
      country: 'UNITED KINGDOM',
      singer: 'Olly Alexander',
      songName: 'Dizzy',
      videoLink: 'https://youtu.be/mvs92WfR8lM?si=aFCm55qyEzn5GrxT',
      info: '"Dizzy" is a song by English singer-songwriter Olly Alexander. It was released on 1 March 2024 through Polydor Records and will represent the United Kingdom in the Eurovision Song Contest 2024. It marks Alexander\'s first release under his own name after the dissolution of Years & Years. The song received mixed reviews from music critics and pays homage to synth-pop music.',
    ),
    SongCard(
      songName: 'Teresa & Maria',
      singer: 'Alyona Alyona\nand Jerry Heil',
      country: 'UKRAINE',
      videoLink: 'https://youtu.be/k_8cNbF8FLI?si=LjzxBe40Gba_tH7-',
      info: '"Teresa & Maria" (Ukrainian: Тереза і Марія [teˈrɛzɐ i mɐˈr⁽ʲ⁾ijɐ]) is a song by Ukrainian singers Alyona Alyona and Jerry Heil. Self-described as a song about hope inspired by Roman Catholic saint Mother Teresa and the Virgin Mary, the song was written by Alyona, Heil, Anton Chilibi, and Ivan Klymenko. The song was released on 11 January 2024 through Enko Music, and is set to represent Ukraine in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'ARMENIA',
      singer: 'Ladaniva',
      songName: 'Jako',
      videoLink: 'https://youtu.be/_6xfmW0Fc40?si=qQza9Q1MTzLIt_wf',
      info: '"Jako" (Armenian: Ժակո, pronounced [ˈʒɑkɔ]) is a song by French-Armenian world music duo Ladaniva. The song was originally released on 29 September 2023 on the duo\'s debut self-titled album as a track. It is set to represent Armenia in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'SWITZERLAND',
      singer: 'Nemo',
      songName: 'The Code',
      videoLink: 'https://youtu.be/kiGDvM14Kwg?si=uM5aUCeVrWCi2iTT',
      info: '"The Code" is a song by Swiss singer Nemo, released on 29 February 2024 by Better Now Records. Described by Nemo as a song that details their experience coming to terms with their non-binary identity, it was written by Nemo and three other songwriters. It is set to represent Switzerland in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'AUSTRALIA',
      singer: 'Electric Fields',
      songName: 'One Milkali',
      videoLink: 'https://youtu.be/tJ2IaHxCvdw?si=mGvCJwkp7zbSyF13',
      info: '"One Milkali (One Blood)" is a song by Australian synth pop duo Electric Fields. Self-described as a song that praises Aboriginal Australian culture and honours band member Zaachariaha Fielding\'s community. It was written by both members of the duo, and has lyrics in English and Yankunytjatjara, an Aboriginal Australian language. It was released on 5 March 2024 by Sony Music Australia. The song is set to represent Australia in the Eurovision Song Contest 2024, which will be held in Malmö, Sweden.',
    ),
    SongCard(
      country: 'SWEDEN',
      singer: 'Marcus & Martinus',
      songName: 'Unforgettable',
      videoLink: 'https://youtu.be/yekc8t0rJqA?si=dBnioTX_YPwI0bls',
      info: '"Unforgettable" is a song by Norwegian music duo Marcus & Martinus, released as a single on 2 March 2024 through Universal Music. The song was written by the duo along with Jimmy "Joker" Thörnfeldt, Joy Deb and Linnea Deb. It will represent Sweden in the Eurovision Song Contest 2024 after winning Melodifestivalen 2024.[1] It reached number one on the Sverigetopplistan chart, becoming Marcus & Martinus\'s first chart-topping song in Sweden.',
    ),
    SongCard(
      country: 'AUSTRIA',
      singer: 'Kaleen',
      songName: 'We Will Rave',
      videoLink: 'https://youtu.be/Kqda15G4T-4?si=zYaO7NA5DOj00m7x',
      info: '"We Will Rave" is a song by Austrian singer Kaleen, released on 1 March 2024 by Warner Music Central Europe. Self-described as a "techno-inspired pop track", it was written by Anderz Wrethov, Jimmy Thörnfeldt, Julie Aagaard, and Thomas Stengaard. The song is set to represent Austria in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'SPAIN',
      singer: 'Nebulossa',
      songName: 'Zorra',
      videoLink: 'https://youtu.be/LJFpexlj9Bs?si=yIzU-0Xu62IOnsY_',
      info: '"Zorra" (pronounced [ˈθora]; Spanish for "Vixen") is a song by husband and wife Spanish synth-pop duo Nebulossa. The song won Benidorm Fest 2024 and will represent Spain in the Eurovision Song Contest 2024 in Malmö. It has so far peaked at number five in Spain and been certified Gold.',
    ),
    SongCard(
      country: 'AZERBAIJAN',
      singer: '	Fahree feat.\nIlkin Dovlatov',
      songName: 'Özünlə apar',
      videoLink: 'https://youtu.be/NNhAk4rVgNc?si=W1nMdiZcdnOXydJA',
      info: '"Özünlə apar" (Azerbaijani pronunciation: [œzynlæ ɑˈpɑɾ];[needs stressed IPA] transl. "Take Me with You") is a song by Azerbaijani singer Fahree featuring Ilkin Dovlatov. It was written by Fahree and four other writers, and was released on 15 March 2024. It is set to represent Azerbaijan in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'SLOVENIA',
      singer: 'Raiven',
      songName: 'Veronika',
      videoLink: 'https://youtu.be/uWcSsi7SliI?si=8yGNuqPC8Ek63Emr',
      info: '"Veronika" (Slovene pronunciation: [ʋɛˈɾòːnika])[1] is a song by Slovenian singer-songwriter Raiven. Described as a "dark alternative pop song"[2] that is inspired by the story of Veronika of Desenice, it was composed by Raiven along with five others, with lyrics also coming from Raiven. The song was self-released on 20 January 2024 through Virgin Music Group, and is scheduled to represent Slovenia in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'BELGIUM',
      singer: 'Mustii',
      songName: "Before the\nParty's Over",
      videoLink: 'https://youtu.be/WCe9zrWEFNc?si=xvFhR5H6sru0DZ_r',
      info: '"Before the Party\'s Over" is a song by Belgian singer and actor Mustii. The song was released on 20 February 2024 by PIAS Recordings, and is set to represent Belgium in the Eurovision Song Contest 2024, in Malmö, Sweden.',
    ),
    SongCard(
      country: 'SERBIA',
      singer: 'Teya Dora',
      songName: 'Ramonda',
      videoLink: 'https://youtu.be/tJyBVRBiyKA?si=15NBNchmSOCC3quN',
      info: '"Ramonda" (Serbian Cyrillic: Рамонда) is a song by Serbian singer and songwriter Teya Dora, which will represent Serbia at the Eurovision Song Contest 2024, after winning Pesma za Evroviziju \'24.',
    ),
    SongCard(
      country: 'CROATIA',
      singer: 'Baby Lasagna',
      songName: 'Rim Tim\nTagi Dim',
      videoLink: 'https://youtu.be/xTBrVNZtnys?si=1-xLiqUFG0Quj5Ao',
      info: '"Rim Tim Tagi Dim" is a song by Croatian musician Marko Purišić, better known as Baby Lasagna. Self-described as a humorous song about the economic emigration of young Croatians, it was written solely by Purišić. The song served as the third single of Baby Lasagna\'s upcoming debut solo album, Demons and Mosquitoes, and was released on 12 January 2024 through Virgin Music Group. It is set to represent Croatia at the Eurovision Song Contest 2024, after winning Dora 2024 by a wide margin.',
    ),
    SongCard(
      country: 'SAN MARINO',
      singer: 'Megara',
      songName: '11:11',
      videoLink: 'https://youtu.be/9NcAJtfhpWA?si=kKcQyYcu0eJftBMt',
      info: '"11:11" (Spanish pronunciation: [ˈonθe j ˈonθe]) is a song by Spanish alternative rock band Megara. It was written and produced by Issa Dante Ramos Solomando, Roberto la Lueta Ruiz, and Sara Jiménez Moral. The song was released on 15 February 2024 by Indica Entertainment. "11:11" is set to be the Sammarinese entry for the Eurovision Song Contest 2024, to be held in Malmö, Sweden.',
    ),
    SongCard(
      country: 'CYPRUS',
      singer: 'Silia Kapsis',
      songName: 'Liar',
      videoLink: 'https://youtu.be/8q5QozrtEPA?si=ZDi604S5DjMbfdMc',
      info: '"Liar" is a song by Australian singer Silia Kapsis, released on 29 February 2024 by K2ID Productions. Self-described as a song that derides "people who live in a fake world with a fake script", it was written by Dimitris Kontopoulos and Elke Tiel. The song is set to represent Cyprus in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'PORTUGAL',
      singer: 'Iolanda',
      songName: 'Grito',
      videoLink: 'https://youtu.be/K5wDGhcDSpQ?si=aRLdm0FXyku5veZb',
      info: '"Grito" (Portuguese pronunciation: [ˈɡɾitu]; transl. "Shout") is a song by Portuguese singer Iolanda, written by herself alongside Alberto "Luar" Hernández. It was released on 18 January 2024 as part of the album for the upcoming Festival da Canção 2024, which it later won, gaining the right to represent Portugal in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'CZECHIA',
      singer: 'Aiko',
      songName: 'Pedestal',
      videoLink: 'https://youtu.be/_iTcX6NlAqA?si=jbvnSr1ziteBO1pj',
      info: '"Pedestal" is a song by Czech singer Aiko, self-released on 22 September 2023 as the lead single of Aiko\'s third studio album, Fortune\'s Child. Self-described as a "self-love, post-breakup anthem", it was written by Aiko and Steven Ansell. The song is set to represent Czech Republic in the Eurovision Song Contest 2024, to be held in Malmö.',
    ),
    SongCard(
      country: 'POLAND',
      singer: 'Luna',
      songName: 'The Tower',
      videoLink: 'https://youtu.be/IhvDkF9XZx0?si=57MtwFL9HUTsZVdJ',
      info: '"The Tower" is a song by Polish singer-songwriter Aleksandra Katarzyna Wielgomas, known monoymously as Luna. Self-described as an account of the journey of strength and self-realization from the depths of darkness and negativity, it was co-written by Luna, Paul Dixon and Max Cooke, and was released on 23 January 2024 by Universal Music Polska. The song is set to represent Poland in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'DENMARK',
      singer: 'Saba',
      songName: 'Sand',
      videoLink: 'https://youtu.be/3pCtdFnv9eQ?si=qCXBsMLVr2B6vRDO',
      info: '"Sand" is a song by Danish singer and actress Saba, released on 25 January 2024 by Warner Music Denmark. Self-described as a song about the feeling of losing control, it was written by Jonas Thander, Melanie Wehbe, and Pil Kalinka Nygaard Jeppesen. The song is set to represent Denmark in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'NORWAY',
      singer: 'Gåte',
      songName: 'Ulveham',
      videoLink: 'https://youtu.be/UipzszlJwRQ?si=xcSKPENenGHy4leN',
      info: '"Ulveham" (pronounced [ˈʉ̂ɫvəˌhɑm]; Norwegian for \'Wolf Pelt\') is a song by Norwegian folk rock and metal band Gåte. It was originally released 12 December 2023 on the EP Vandrar as a track. It was later shortened and re-published as a single upon its selection to participate in Melodi Grand Prix 2024. The song ultimately won the selection and will thus represent Norway in the Eurovision Song Contest 2024. It is Norway\'s first Eurovision entry since 2006 to be sung in Norwegian.The opening features a traditional kulokk, a herding call, sourced from an old recording featuring Marit Jensen Lillebuen. The story of the lyrics are based on an almost thousand-year-old Scandinavian medieval ballad.',
    ),
    SongCard(
      country: 'ESTONIA',
      singer: '5miinust\nand Puuluup',
      songName: '(Nendest) narkootikumides\nei tea me (küll) midagi',
      videoLink: 'https://youtu.be/zY6RbPaTNUc?si=YooL78tK52Jpnc7s',
      info: '"(Nendest) narkootikumidest ei tea me (küll) midagi"[needs Estonian IPA] (transl. We (sure) know nothing about (these) drugs) is a collaborative song by Estonian hip hop group 5miinust and Estonian folk duo Puuluup, released on 8 December 2023 by Universal Music Oy. Self-described as a song that was inspired by a comment that a band member made about drugs during a car trip, it was written by members of both groups. The song is set to represent Estonia in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'NETHERLANDS',
      singer: 'Joost Klein',
      songName: 'Europapa',
      videoLink: 'https://youtu.be/gT2wY0DjYGo?si=HwUY5zqwkUTSOw2D',
      info: '"Europapa" (Dutch pronunciation: [ˈøːroːˌpɑpaː]; transl. "Eurodaddy") is a song by Dutch musician Joost Klein. Self-described as a "very Dutch" 1990s-style song, it was written by Klein along with six other songwriters. The song was released on 29 February 2024 and is set to represent the Netherlands in the Eurovision Song Contest 2024. It peaked at number one on the singles charts of the Netherlands and Flanders.',
    ),
    SongCard(
      country: 'FINLAND',
      singer: 'Windows95man',
      songName: 'No Rules!',
      videoLink: 'https://youtu.be/8Wi7fhswoBA?si=H4w1rBghHdgOOI1-',
      info: '"No Rules!" is a song by Finnish visual artist Teemu Keisteri, known professionally by his stage name persona, Windows95man. Self-described as a song that is inspired by Keisteri\'s life mantra of not taking everything seriously. It was written and composed by Henri Piispanen, Jussi Roine, and Keisteri, and released on 16 January 2024 through All Day Entertainment Oy. The song is set to represent Finland in the Eurovision Song Contest 2024. It peaked at number six in Finland.',
    ),
    SongCard(
      country: 'MOLDOVA',
      singer: 'Natalia Barbu',
      songName: 'In the Middle',
      videoLink: 'https://youtu.be/Jom9sNL5whs?si=j_OVgCfWqJdCF4GZ',
      info: '"In the Middle" is a song by Moldovan singer Natalia Barbu. The song was written by Barbu and Khris Richards. It was released on 19 January 2024 by Ragoza Music. "In the Middle" is set to represent Moldova in the Eurovision Song Contest 2024, which will be held in Malmö, Sweden.',
    ),
    SongCard(
      country: 'FRANCE',
      singer: 'Slimane',
      songName: 'Mon amour',
      videoLink: 'https://youtu.be/tfoOop2HXxQ?si=BnCWHN52W8jHq-8B',
      info: '"Mon amour" (French pronunciation: [mɔ̃n‿amuʁ]; transl. "My love") is a song by French singer Slimane, released on 8 November 2023 by Noé Music. Described as an "ode to romance and love", it was written and composed by Slimane, Yaacov Salah, and Meïr Salah. The song is scheduled to represent France in the Eurovision Song Contest 2024. It has so far entered the charts in France and Belgium and been certified gold by the SNEP.',
    ),
    SongCard(
      country: 'MALTA',
      singer: 'Sarah Bonnici',
      songName: 'Loop',
      videoLink: 'https://youtu.be/l6eS60n4wg8?si=R6T29iFQV-SQqfje',
      info: '"Loop" is a song by Maltese singer Sarah Bonnici. Self-described as a positive love song, it was written by Bonnici alongside seven other songwriters. It was officially self-released on 14 March 2024, and is set to represent Malta in the Eurovision Song Contest 2024 in Malmö.',
    ),
    SongCard(
      country: 'GEORGIA',
      singer: 'Nutsa Buzaladze',
      songName: 'Firefighter',
      videoLink: 'https://youtu.be/blMwY8Jabyk?si=kisNo2PZVobtH4eO',
      info: '"Firefighter" is a song by Georgian singer Nutsa Buzaladze, released on 11 March 2024 by Stop Talking. Written by Ada Skitka and Darko Dimitrov, it is set to represent Georgia in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'LUXEMBOURG',
      singer: 'Tali',
      songName: 'Fighter',
      videoLink: 'https://youtu.be/6CNuXpdyYmE?si=6p5IPOh6DABRKFZi',
      info: '"Fighter" is a song by Israeli-born Luxembourgish singer-songwriter Tali Golergant, written by Ana Zimmer, Dario Faini, Manon Romiti, and Silvio Lisbonne. It was released on 12 January 2024 by Bel Air Records. Self-described as a song about how humans suffer and persevere through struggles, the song is set to represent Luxembourg in the Eurovision Song Contest 2024 – the first Luxembourgish entry in the contest for over 30 years, with the country last competing in 1993.',
    ),
    SongCard(
      country: 'GERMANY',
      singer: 'Isaak',
      songName: 'Always on the Run',
      videoLink: 'https://youtu.be/8b5gcgXcWgk?si=EU1bfwkPRMgmzvQt',
      info: '"Always on the Run" is a song by German singer-songwriter Isaak, released on 19 January 2024 through Good Kid Records and Polydor Records. Self-described as an insight into the singer\'s "conflicting" mind through a "powerful sound" paired with "calm moments", it is set to represent Germany in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'LITHUANIA',
      singer: 'Silvester Belt',
      songName: 'Luktelk',
      videoLink: 'https://youtu.be/OrL668EQRu0?si=912d3bbU-5kVuumK',
      info: '"Luktelk" (Lithuanian: [ˈlʊktʲɛlk]; transl. "Wait") is a song by Lithuanian singer-songwriter Silvester Belt. It was self-released on 11 January 2024. The song is set to represent Lithuania in the Eurovision Song Contest 2024, to be held in Malmö, Sweden, after winning Eurovizija.LT.[1] It peaked at number one in his home country of Lithuania.',
    ),
    SongCard(
      country: 'GREECE',
      singer: 'Marina Satti',
      songName: 'Zari',
      videoLink: 'https://youtu.be/uTYalXf184A?si=kEsgunr7IDRpj_co',
      info: '"Zari" (Greek: Ζάρι, pronounced [ˈzari]; transl. "Dice" [sg.]; stylised in all caps) is a song by Greek singer Marina Satti, co-written by Satti with eight other songwriters and released on 7 March 2024 by Golden Records. It is set to represent Greece at the Eurovision Song Contest 2024. Satti describes it as a song that aims to tell the "real characteristics" of young Greek people and their culture. It peaked at number one in Greece and has been certified platinum by the IFPI Greece.',
    ),
    SongCard(
      country: 'LATVIA',
      singer: 'Dons',
      songName: 'Hollow',
      videoLink: 'https://youtu.be/p8FNO0DtBng?si=f4el98mlUeiHz-8D',
      info: '"Hollow" is a song by Latvian singer-songwriter Dons. Self-described as a song that speaks about how one\'s inner insecurities can hold someone down, the song was written by Artūrs Šingirejs, Kate Northrop, and Liam Geddes. The song was released on 2 January 2024 by Universal. It is set to represent Latvia in the Eurovision Song Contest 2024, which will be held in Malmö, Sweden.',
    ),
    SongCard(
      country: 'ICELAND',
      singer: 'Hera Björk',
      songName: 'Scared of Heights',
      videoLink: 'https://youtu.be/OouUsCZ3xkM?si=T3nMGT5LfDGoXPyf',
      info: '"Scared of Heights" (Icelandic: Við förum hærra [ˈvɪːð ˈfœːrʏm ˈhairːa]; transl. "We go higher") is a song by Icelandic singer Hera Björk, written by Ferras Alqaisi, Ásdís María Viðarsdóttir, Jaro Omar and Michael Burek. It was released on 28 January 2024 by Alda Music. The song is set to represent Iceland in the Eurovision Song Contest 2024.',
    ),
    SongCard(
      country: 'ITALY',
      singer: 'Angelina Mango',
      songName: 'La noia',
      videoLink: 'https://youtu.be/TO85laH-ATY?si=DwPlrFii1kRryd9e',
      info: '"La noia" (Italian pronunciation: [la ˈnɔːja]; transl. "Boredom") is a song by Italian singer Angelina Mango. It was written by Mango and Madame and produced by Dardust, and released on 7 February 2024.[1][2] The song was Angelina Mango\'s winning entry for the Sanremo Music Festival 2024, the 74th edition of Italy\'s musical festival which also doubles as a selection of the act for the Eurovision Song Contest,[3][4] and will represent the country at the 2024 event. The song was also recognized with the "Giancarlo Bigazzi" Award for the best musical composition.[5]"La noia" reached number four on the Italian singles chart and has been certified double platinum by the FIMI, for selling over 200,000 units. It has also reached the charts in Switzerland, San Marino, and Croatia.',
    ),
    SongCard(
      country: 'IRELAND',
      singer: 'Bambie Thug',
      songName: 'Doomsday Blue',
      videoLink: 'https://youtu.be/ZGRXRrlIspY?si=IVCAr6ZH6rq03a9F',
      info: '"Doomsday Blue" is a song by Irish singer-songwriter Bambie Ray Robinson, known by their stage name, Bambie Thug. Self-described as "an electro-metal breakdown", it was written by Robinson, Olivia Cassy Brooking, Sam Matlock, and Tyler Ryder. The song was self-released on 13 October 2023 as part of their first extended play, Cathexis, and is set to represent Ireland in the Eurovision Song Contest 2024. "Doomsday Blue" became Robinson\'s first charting song in their home country.',
    ),
    SongCard(
      country: 'ISRAEL',
      singer: 'Eden Golan',
      songName: 'Hurricane',
      videoLink: 'https://www.bing.com/ck/a?!&&p=5ca55cdd5293ee4eJmltdHM9MTcxMjk2NjQwMCZpZ3VpZD0wZDE1YTJmZS1iMDgxLTZlMDQtMjg1Zi1iMDY4YjEzMzZmMzQmaW5zaWQ9NTg1MA&ptn=3&ver=2&hsh=3&fclid=0d15a2fe-b081-6e04-285f-b068b1336f34&u=a1L3ZpZGVvcy9yaXZlcnZpZXcvcmVsYXRlZHZpZGVvP3E9aXNyYWVsK2V1cm92aXNpb24rMjAyNCZtaWQ9NzVBNThBNTQ4QUNDNzA0MEVCRUI3NUE1OEE1NDhBQ0M3MDQwRUJFQiZGT1JNPVZJUkU&ntb=1',
      info: '',
    )
  ];
